import Head from "next/head";
import ComboList from "@/components/selectList/comboList";
import { useState } from "react";
import { ComboItem, selRangeItem } from "@/interfaces";
import SelRange from "@/components/selectList/selRange";
import Link from "next/link";

export default function Home() {
  const data: ComboItem[] = [
    { id: 1, name: "あああ" },
    { id: 2, name: "いいい" },
    { id: 3, name: "ううう" },
    { id: 4, name: "えええ" },
    { id: 5, name: "その他" },
  ];

  const data2: ComboItem[] = [
    { id: 1, name: "はい" },
    { id: 2, name: "いいえ" },
  ];

  const data3: selRangeItem = {
    min: 0,
    max: 100,
    init: 50,
  };

  const initComboItem: ComboItem = { id: 0, name: "" };
  const [selectedItem, setSelectedItem] = useState<ComboItem>(initComboItem);
  const [selected2Item, setSelected2Item] = useState<ComboItem>(initComboItem);
  const [value, setValue] = useState<number>(data3.init);

  return (
    <>
      <Head>
        <title>Next Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>アンケート</h1>
      <Link href="/">
        <p>戻る</p>
      </Link>
      <ComboList
        name={"質問1あああああああああああああああああああああああああ"}
        items={data}
        length={data.length}
        setItem={(item) => setSelectedItem(item)}
        stVisible={selectedItem === initComboItem}
      />
      <ComboList
        name={"質問2"}
        items={data2}
        length={data2.length}
        setItem={(item) => setSelected2Item(item)}
        stVisible={selected2Item === initComboItem}
      />
      <SelRange
        name={"質問3"}
        item={data3}
        value={value}
        unit={"%"}
        setValue={(value) => setValue(value)}
      />
    </>
  );
}
