import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>食事メモ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>食事メモ</h1>
      <Link href="/">
        <p>戻る</p>
      </Link>
    </>
  );
}
