import Head from "next/head";
// import { Inter } from "next/font/google";
import ComboList from "../components/selectList/comboList";
import { useState } from "react";
import { ComboItem } from "@/interfaces";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const initComboItem: ComboItem = { id: 0, name: "" };
  const [selectedItem, setSelectedItem] = useState<ComboItem>(initComboItem);

  const data: ComboItem[] = [
    { id: 1, name: "あああ" },
    { id: 2, name: "いいい" },
    { id: 3, name: "ううう" },
    { id: 4, name: "えええ" },
  ];

  // useEffect(() => {
  //   console.log(selectedItem);
  // }, [selectedItem]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>あああ</h1>
      <p>
        選択されたものは: {selectedItem.id}:{selectedItem.name}
      </p>
      <ComboList
        name={"質問1"}
        items={data}
        length={data.length}
        setItem={(item) => setSelectedItem(item)}
      />
    </>
  );
}
