import Head from "next/head";
import Link from "next/link";
import styled, { createGlobalStyle } from "styled-components";

const DivComponent = styled.div`
  /* width: 767px; */
  width: 325px;
  max-width: 100vw;
  border-bottom: 1px solid black;
`;

const GlobalStyle = createGlobalStyle`
  * {
    margin: 0;
    padding: 0;
    font-family: sans-serif;
    box-sizing: border-box;
    a {
        /* color: $base-color; */
    }
  }
`;

export default function Home() {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>食事メモ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>食事メモ 一回の食事ごと</h1>
      <DivComponent></DivComponent>
      <Link href="/">
        <p>戻る</p>
      </Link>
    </>
  );
}
