name: CI-check

on: push

jobs:
  check-next3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Check lint
        run: yarn lint

      - name: Check build
        run: yarn build
